apiVersion: v1
kind: Secret
metadata:
  name: retrieval-secrets
  namespace: retrieval-system-yaml
  labels:
    app: retrieval-vector-storage
type: Opaque
data:
  POSTGRES_PASSWORD: jkdnckfjnkf
  MINIO_ROOT_USER: djkncfkd
  MINIO_ROOT_PASSWORD: kfdcnfrjknfvjkf
  AUTH0_DOMAIN: kjdnvfjknvfjk
  AUTH0_AUDIENCE: dkjnvfjnvkfj