apiVersion: v1
kind: Secret
metadata:
  name: langchain-backend-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "agent-service.labels" . | nindent 4 }}

type: Opaque

data:
  # MONGODB URI
  MONGO_URI: {{ .Values.secrets.mongo.mongoUri | b64enc | quote }}

  #Auth0 Config for UI
  UI_AUTH0_DOMAIN: {{ .Values.secrets.auth0.domain | b64enc | quote }}
  UI_AUTH0_AUDIENCE: {{ .Values.secrets.auth0.audience | b64enc | quote }}

  # M2M Auth0 for MCP RAG server
  RETRIEVAL_MCP_CLIENT_ID: {{ .Values.secrets.m2m.clientId | b64enc | quote }}
  RETRIEVAL_MCP_CLIENT_SECRET: {{ .Values.secrets.m2m.clientSecret | b64enc | quote }}
  RETRIEVAL_MCP_AUDIENCE: {{ .Values.secrets.m2m.audience | b64enc | quote }}
  RETRIEVAL_MCP_DOMAIN: {{ .Values.secrets.auth0.domain | b64enc | quote }}

  # HuggingFace Token
  HF_TOKEN: {{ .Values.secrets.hfToken | b64enc | quote }}

  # Tavily Token
  TAVILY_API_KEY: {{ .Values.secrets.tavilyApiKey | b64enc | quote }}

  # Langfuse credentials
  LANGFUSE_SECRET_KEY: {{ .Values.secrets.langfuseSecretKey | b64enc | quote }}
  LANGFUSE_PUBLIC_KEY: {{ .Values.secrets.langfusePublicKey | b64enc | quote }}
  LANGFUSE_BASE_URL: {{ .Values.secrets.langfuseBaseUrl | b64enc | quote }}
  POSTGRES_ADMIN_PASSWORD: {{ .Values.secrets.postgresAdminPassword | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.langraphPostgresPassword | b64enc | quote }}
  POSTGRES_URI: {{ printf "postgresql://%s:%s@postgres-headless.%s.svc.cluster.local:5432/%s" .Values.langraph.database.user .Values.secrets.langraphPostgresPassword .Values.global.namespace .Values.langraph.database.name | b64enc | quote }}