apiVersion: v1
kind: ConfigMap
metadata: 
    name: mcp-server-config
    namespace: {{ .Values.global.namespace }}
    labels:
    {{- include "mcp_server.labels" . | nindent 4 }}

data:
    RETRIEVAL_BASE_URL: {{ .Values.config.retrieval_base_url | quote }}
