apiVersion: v1
kind: Secret
metadata:
  name: mcp-server-secrets
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "mcp_server.labels" . | nindent 4 }}

type: Opaque

data:

  # M2M Auth0 for RAG service
  AUTH0_DOMAIN: {{ .Values.secrets.m2m.domain | b64enc | quote }}
  AUTH0_CLIENT_ID: {{ .Values.secrets.m2m.clientId | b64enc | quote }}
  AUTH0_CLIENT_SECRET: {{ .Values.secrets.m2m.clientSecret | b64enc | quote }}
  AUTH0_AUDIENCE: {{ .Values.secrets.m2m.audience | b64enc | quote }}
  AUTH0_LANGCHAIN_CLIENT_AUDIENCE: {{ .Values.secrets.mcpLangchainClient.audience | b64enc | quote }}
  AUTH0_LANGCHAIN_CLIENT_DOMAIN: {{ .Values.secrets.mcpLangchainClient.domain | b64enc | quote }}