apiVersion: v1
kind: ConfigMap
metadata:
  name: hugg-backend-config
  namespace: retrieval-system
  labels:
    app: hugg-backend
    component: backend
data:

  MONGO_DB_NAME: "hugg_chat_db"
  MONGO_MAX_POOL_SIZE: "50"
  MONGO_MIN_POOL_SIZE: "1"

  # AI Model Configuration
  MODEL_ID: "meta-llama/Llama-3.2-3B-Instruct"
  API_BASE_URL: "https://router.huggingface.co/v1/"
  MAX_TOKENS: "1024"
  TEMPERATUR: "0.7"

  # Retrieval Service COnfig (local service in the same namespace)
  RAG_SERVICE_URI: "http://retrieval-api:8001"

  # Ollama Configuration 
  OLLAMA_BASE_URL: "http://host.docker.internal:11434"
  OLLAMA_MODEL: "llama3.1:8b"

  # Application settings
  ENV: "development"
  debug: "false"
