apiVersion: v1
kind: Secret
metadata:
  name: hugg-backend-secrets
  namespace: retrieval-system
  labels:
    app: hugg-backend
    component: backend

type: Opaque

data:
  # MONGODB URI
  MONGO_URI: ajcbdjcjd

  #Auth0 Config
  AUTH0_DOMAIN: sejcnjdk
  AUTH0_AUDIENCE: cjrhjrnfrnfrj

  # M2M Auth0 for RAG service
  CLIENT_ID: jnfcrjnf=
  CLIENT_SECRET: refnrjnfjrfjnr==
  AUDIENCE: rjfnrjfjkrjfrnj

  # HuggingFace Token
  HF_TOKEN: rfjnkrjkjfnrk==
